### ISSUE TITLE
antony's portfolio

### ISSUE THREAD

**Issue by afm2105** [ga-wdi-exercises/portfolio_pages#69]
https://github.com/afm2105/afm2105.github.io

**Comment by adambray** [comment]
https://github.com/afm2105/afm2105.github.io/blob/master/style.css#L32
Note there's no `p1` tag, so this isn't a valid selector!

**Comment by adambray** [comment]
There's a lot of duplication between your h2, h3, and h4 rules:
https://github.com/afm2105/afm2105.github.io/blob/master/style.css#L32

You could shorten using the `,` to select multiple tags:

``` css
h2, h3, h4 {
    font-size: 33px;
    text-align:center;
}
```

**Comment by adambray** [comment]
For your CSS, make sure to use consistent spacing:
https://github.com/afm2105/afm2105.github.io/blob/master/style.css#L8

``` css
nav{
    float: left; // good!
    float:left; // not good! note the lack of space after the colon.
  }
```
