### ISSUE TITLE
Portfolio (Masatoshi Nishiguchi)

### ISSUE THREAD

**Issue by mnishiguchi** [ga-wdi-exercises/portfolio_pages#87]
[https://github.com/mnishiguchi/mnishiguchi.github.io](https://github.com/mnishiguchi/mnishiguchi.github.io)

After considering for a while, I decided to build upon my existing live Jekyll website because I really feel passionate about improving it. I added a simple timeline layout as well as clean up contents such as skills and experience.

``` yaml
comfort:
  level: 5
  message:
complete:
  level: 4
  message: In terms of basic structure and layout, it can be said that it is complete. For this particular project, I will move towards marketing myself from now on.
```
